version: '3.7'
services:
  web:
    image: nginx:1.21
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/:/var/www/html
    container_name: "laravel_nginx"
    tty: true

  app:
    build: ./
    volumes:
      - ./nginx/:/var/www/html
    container_name: "laravel_php-fpm"
    tty: true

  node:
    image: node:16.14.0
    volumes:
      - ./nginx/:/var/www/html
    working_dir:  /var/www/html/
    container_name: "laravel_node"
    platform: "linux/arm64/v8"
    tty: true

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/:/var/lib/mysql
    platform: "linux/x86_64"
    container_name: "laravel_mysql_server"
    tty: true